apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apic-apis
  namespace: openshift-gitops
spec:
  destination:
    namespace: cp4i
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./components/apiconnect/base/apis/
    targetRevision: cp4i2023.4.1
    repoURL: https://github.com/lucianoraso/hypersonic-lightweight-cp4i.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
